### PR TITLE
Fix bug where text is not truncated after "See Less" button is clicked

### PR DESCRIPTION
**Pull request by nlfurniss**
Fixed bug where the text was not retruncated after clicking the "See Less" button. Also fixed the test that didn't catch the issue.

### CODE REVIEW

**Comment by nickiaconis** [comment]
This looks good to me, and I've verified the tests pass locally for all scenarios, so I'll merge it. I need to figure out what's going on with the tests before I can release though. The beta and canary scenarios are failing, but only on CI. It's happening for the master branch as well.

**Comment by nlfurniss** [comment]
I ran the tests against beta and canary locally and they failed. When I did an npm update and got the latest version of `ember-cli-qunit` (1.4.2 from 1.4.0) both `canary` and `beta` pass. 

Not sure how to force an update on Travis-ci

**Comment by nickiaconis** [comment]
Interesting. I wasn't able to reproduce the failure, probably because I had
done a fresh checkout. I can manually bump the version in `package.json`.
That should force Travis to update.

**Comment by nickiaconis** [comment]
That did the trick. Thanks @nlfurniss! I'll cut a new release now.

**Pull request merged**
