### PR TITLE
Address deprecation of arguments in component lifecycle hooks.

### PR DESCRIPTION
**Pull request by LuiNova**
Ember will stop passing arguments to component lifecycle hooks.
See https://goo.gl/pfxVsS for more details.

### CODE REVIEW

**Comment by LuiNova** [comment]
Nick let me know what you think about this approach

**Comment by nickiaconis** [comment]
Hi Luis, thanks for the PR!

The tests are passing, and the code looks okay. I'm curious though: why build the change detection yourself rather than rely on a community solution like [`ember-diff-attrs`](https://github.com/workmanw/ember-diff-attrs)?

**Comment by LuiNova** [comment]
Had a few problems with `ember-diff-attrs`, I think the root cause of the problems came down to this:

```
Since this addon is implemented as a macro, it cannot easily utilize a component's init call to setup. Because of this, we are unable to determine what has changed the first time didUpdateAttrs is called.
```

**Comment by nickiaconis** [comment]
I had some spare time tonight, so I went ahead and tackled this. Hope you don't mind.

**Pull request closed without merging**
