### PR TITLE
Ensure that ellipsizedSpan exists before moving it into wrappingSpan

### PR DESCRIPTION
**Pull request by Joelkang**

### CODE REVIEW

**Comment by nickiaconis** [comment]
Hi @Joelkang! Thanks for the PR. Could you please write a test for this and retain the empty line at the end of the file?

**Comment by jamesmenera** [comment]
I also fixed this bug in Pull Request #7 because I needed to use it in production app. Please consider adding this pull request or mine to fix bug.

**Comment by jamesmenera** [comment]
My pull request also fixes fastboot support though. Pretty sexy if you ask me. Just looking for input though

**Comment by nickiaconis** [comment]
I believe #29 covers this.

**Pull request closed without merging**
