### PR TITLE
Make this add-on Fastboot Safe

### PR DESCRIPTION
**Pull request by jamesmenera**
Removed the self invoking function and passed `window` and `document` in a safe time to use those references

### CODE REVIEW

**Comment by jamesmenera** [comment]
Hey, I am willing to update this anyway you want I just needed to make this work for a important fastboot project. Just let me know what updates you want me to make. I changed up the format a bit to understand what this was doing so I could fix it. Not really sure how to add tests to prove it is fastboot safe, but it is because we using it in production. So I can assure you it is. Please add feedback, wanting to contribute back.

**Comment by jamesmenera** [comment]
Thanks for the hard work, let me help you out. 😁

**Comment by jamesmenera** [comment]
Also if you have any good ideas on writing a fastboot test please feel free to comment back, our team is relatively new to building and using fastboot env's and not 100% sure how to write those tests for that env yet.

**Comment by nickiaconis** [comment]
Hi @jamesmenera! Thanks for putting together this pull request. I haven't used fastboot, so you're the expert. 😜 

You'll likely need to rebase as I've recently merged another PR.

As a starter for feedback, please make sure the code passes linting. As far as I can tell, that's the main reason Travis CI is failing. Also, I really like the direction you're headed with refactoring the clamp function, but it would be better, organizationally, if it were a separate PR. Take care of those, clean up commented out code and trailing whitespace, and I think this will be ready to merge.

**Comment by nickiaconis** [comment]
Resolved by #29

**Pull request closed without merging**
